version: '3'

services:
  app:
    build: .
    tty: true
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - .:/app
      - node_modules-volume:/app/node_modules
    depends_on:
      - db
    environment:
      - DATABASE_URL='${DATABASE_URL}'
      - TEST_DATABASE_URL='${TEST_DATABASE_URL}'
  db:
    build:
      context: '.'
      dockerfile: 'db.Dockerfile'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: whiteboard
    volumes:
      - whiteboard-data:/var/lib/postgresql/data
volumes:
  whiteboard-data:
    external: true
  node_modules-volume:
