name: CI

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup docker compose
        shell: bash
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
        run: |
          docker volume create --name=whiteboard-data
          docker-compose up -d
          docker-compose exec -T app bash test.sh
